# Ultralytics format dataset YAML

path: data/my_dataset/dota/dota-v1.0-split  # folder created by split

train: images/train
val: images/val
test: images/test  # optional

names:
  0: plane
  1: ship
  2: storage tank
  3: baseball diamond
  4: tennis court
  5: basketball court
  6: ground track field
  7: harbor
  8: bridge
  9: large vehicle
  10: small vehicle
  11: helicopter
  12: roundabout
  13: soccer ball field
  14: swimming pool
