train: ../../../../data/my_dataset/dota/dota-v1.0/train/images
val: ../../../../data/my_dataset/dota/dota-v1.0/val/images
test: ../../../../data/my_dataset/dota/dota-v1.0/test/images

nc: 15  # or however many classes you have
names:
  - plane
  - baseball-diamond
  - bridge
  - ground-track-field
  - small-vehicle
  - large-vehicle
  - ship
  - tennis-court
  - basketball-court
  - storage-tank
  - soccer-ball-field
  - roundabout
  - harbor
  - swimming-pool
  - helicopter
