# my_dataset.yaml

path: ../data/my_dataset/visdrone  # dataset root dir

train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

labels_train: C:/Users/burak/OneDrive/Desktop/Git Repos/drone-obj-detection-lightweight-ai/data/my_dataset/visdrone/labels/train
labels_val:   C:/Users/burak/OneDrive/Desktop/Git Repos/drone-obj-detection-lightweight-ai/data/my_dataset/visdrone/labels/val

# Classes
nc: 10  # number of classes
names: ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor']  # class names
